# Generated by Django 2.2.14 on 2021-01-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjcars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='soso.jpg', upload_to='profile_pics'),
        ),
    ]
