# Generated by Django 2.2.14 on 2021-01-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjcars', '0003_auto_20210104_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='cover',
            field=models.ImageField(default='soso.jpg', upload_to='images/'),
        ),
    ]
