# Generated by Django 2.2.14 on 2021-01-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gjcars', '0004_auto_20210104_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img1',
            field=models.ImageField(default='soso.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='img2',
            field=models.ImageField(default='soso.jpg', upload_to='images/'),
        ),
    ]
